### ISSUE TITLE
Builders won't compile after upgrading rxjs to 6.4.0

### ISSUE THREAD

**Issue by DenysVuika** [alexzuza/angular-plugin-architecture#1]
To reproduce the issue, run the following commands:

```sh
ng update rxjs
npm run postinstall
```

**Comment by alexzuza** [comment]
Hey, Denys!
Thank you pointing this out.
It looks like `@angular-devkit/core@7.3.6` package has dependency on `rxjs@6.3.3`.
As a result, it contains its own `node_modules/rxjs` version which conflicts with updated version

![conflict](https://user-images.githubusercontent.com/4223314/55432735-b7e8de00-55a4-11e9-9659-1995ba72919b.png)

To remedy this you can add `rxjs` to `paths` in

**tsconfig.builders.json**

```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "module": "commonjs",
    "outDir": "./plugin-builder",
    "importHelpers": false,
    "sourceMap": false,
    "target": "es6",
    "paths": {
      "rxjs": ["./node_modules/rxjs"]
    }
  },
  "files": [
    "./plugin-builder/index.ts"
  ]
}
```

**Comment by DenysVuika** [comment]
Thanks, @alexzuza , I will try. Other than that - awesome article and demo project! It is going to help my team a lot, thanks.

**Comment by DenysVuika** [comment]
Still struggling to use your project with the latest RxJs or Angular CLI. It seems you've been using some legacy API that got deprecated in later versions. 

```
plugin-builder/index.ts:1:64 - error TS2307: Cannot find module '@angular-devkit/build-angular'.

1 import { BrowserBuilder, NormalizedBrowserBuilderSchema } from '@angular-devkit/build-angular';

plugin-builder/index.ts:114:27 - error TS2339: Property 'deleteOutputPath' does not exist on type 'PluginBuilderSchema'.

114     builderConfig.options.deleteOutputPath = false;
```

RxJs mapping does not do the trick either :(

Have you managed to get your example up and running with the fresh versions of libs?
